# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Pull Request CI

on: [ pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2

#      - name: Setup Docker ğŸ‹
#        uses: docker-practice/actions-setup-docker@1.0.8
#
#      - name: Build Dockerfile ğŸ‹
#        run: docker build -t number-munchers .
#
#      - name: Run Docker Container ğŸƒâ€â™€ï¸
#        run: docker run --rm -p 80:80 -d number-munchers:latest
#
#      - name: Setup Node â˜•
#        uses: actions/setup-node@v1
#        with:
#          node-version: 12.x
#
#      - name: Install ğŸ”§
#        run: npm ci
#
#      - name: Functional Test ğŸ”’
#        run: APP=http://localhost/ npm run selenium
